import Head from "next/head";
import ComingSoon from "../src/components/ComingSoon";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Palma View</title>
				<meta
					name="description"
					content="Generated by Palma View LLC"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<ComingSoon />
			</main>
		</div>
	);
}
